version: "3.9"
services:
  data-simulator:
    container_name: data-simulator
    build: ./data-simulator
    ports:
      - "3000:3000"
  batch-layer:
    container_name: batch-layer
    build: ./batch-layer
    ports:
      - "3000:3000"
    depends_on:
      - data-simulator
  redis:
    container_name: redis
    image: "redis"
    ports:
      - "6379:6379"
  speed-layer:
    depends_on:
      - data-simulator
      - redis
    build: ./speed-layer
    container_name: speed-layer
