version: "3.9"
services:
  data-simulator:
    container_name: data-simulator
    build: ./data-simulator
    depends_on:
      - batch-layer
      - speed-layer
  batch-layer:
    container_name: batch-layer
    build: ./batch-layer
    ports:
      - "3000:3000"
  redis:
    container_name: redis
    image: "redis"
    ports:
      - "6379:6379"
  speed-layer:
    depends_on:
      - redis
    ports:
      - "4000:4000"
    build: ./speed-layer
    container_name: speed-layer
    ports:
      - "4000:4000"
