version: "3"
services:
  web:
    build: .
    ports: 
      - "6062:6062"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    expose:
      - 6379
    restart: always

