version: "3.9"
services:
  app:
    build: .
    ports:
      - "5000:5000"
      redis:
        image: "redis:alpine"
        ports:
          - "6379:6379"
        expose:
          - 6379
        restart: always